$ANSIBLE_VAULT;1.1;AES256
38306638333030633539623262393661343963313731653537386266633266313035643531396665
3563656561383130363237646364666635343763656463650a663836326665393763336337613839
61313337373831653237333235396535363936643138633836346338623038653765643766366333
3566353966653234330a626664613964633564366265663664303631323331636361303636346638
38306130323933376634326332666261313162616637363464663233653335666338393863643866
36363865666161613238386634326266316437326637313937353031353831396337353639646464
37613235616366393161376363303536623930663263356363626364623532383139303839626462
34376363633834393932306233343262326663653065613434333238303733613836646638383139
30343635366437303061636535396161353331656161633739633263343162383938626432666136
63666261313663643765313630653234373230313033316663396138393430343731313536323438
39316132643034653962633932346562656237653334376530306336313335356635386233346664
66326161386330653035313165343564663339623733363334313062666631653836633139623162
30626536333062333433386237333634613034633561356631373365306435333131343431363635
65653632643562333530623232343632623664623238653163646136366662356538643836396237
343439616133656139326565383038393539
