$ANSIBLE_VAULT;1.1;AES256
38326332666530663732666230373965613134316436346438633639353635383861356365656263
6562653630663837393763393936363030636432386337330a646531636236656439323136616138
32656533613339666335316165376661633234333632313264313061363365316437303535363763
6433613533656163300a303534393964633963303831343630313338623238643765333562646565
65346533373265366331363832396632653165303466656233393334343836393832366663613866
35346165613866313861303639373361303563633737656333666162366634663339353566386164
39333666363532353261373432393438303938303161366135373632376465633733326331393466
35343435633837623239656562303662323031666164303266323930653039363765333561623361
63326239353639623634393534316566333431386666303030613164343531386133643661613535
63316534396637636539626633663361663966316333313130336665343833663737636666666233
35303362303465303537306166313330353636323164343566623837346532396532656565313336
32633532326232333761666465623731366562633566666430616131343534333436613566316135
64386363363438303065616633343261633032343661323837316235333630363539343332343632
62643762383636343161396135653565643937633565303438303762333335663966303136613264
66663766376137306330346464353037623562636531666165363630343866383638653836373032
36386337303736303964313263353565616633363131356630663334646364323161646565336336
30623839623266626263363265623934646465303539336161623161373166323630616264643338
63613237656566326565353635373561356365386434393161323064353964383163656666386365
63316137313432656662336163653338383564656564656439613931626230303932363034316162
64666536306133353338653232366661386164653266373464333461383139393537306536663431
64633636613132333264646436326139396330663466316236346634616234363038626366613962
37666662336132643039353162633865653862613961636139653939653961666665393135656234
35333439393466383737313332353861656463336330633765313165323938303865656435626536
38646463666532373561626335626336643232636662333765343039663833383438343362363038
36653233316233613434373436343333383461393438366639306662386136373362353761363164
6630616533616462376631336536386264363139363132656331
