$ANSIBLE_VAULT;1.1;AES256
65646133343165313335613161643765306161356131383265363936393233313233313165396464
3737663961656138613730303637313939653461633961370a326139346466393534363836303665
62366234613330353436613261633837623865306431663532363932666435356330373064343033
3934666637353132650a656237666561666138353534356664373030313436383630383562346134
31663266663264646462653930363861386432313366623761376530336633363965663666306265
63666235333038623164663665343862663930636539376166383865636532333136613738653331
34613037653465613634636539336437613764663234366461366131653633313032383861653764
65633233393062663539306562383866346262356563373063306539306662373865393865663836
34663030386161363737636538353639363164363130396130623966353261623033663437393034
30336230326536353566663337653564373939333837326630653636326633326539623934303131
30363339393032323362323531353866366265663666313061326437653463346561663734353735
38356432393762353161343263306136623038623739353964353832623935393131646536653931
30313162393435616635646439306234393237376566386366623737646139306637636166356431
6536363766356231376462646436376431333931653166636230
